<?php

use App\Models\ActivityLog;
use App\Models\Series;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('it creates an activity log when a series is updated', function () {
    $user = User::factory()->create();
    $this->actingAs($user);

    $series = Series::factory()->create([
        'user_id' => $user->id,
        'title' => 'Original Title',
        'status' => 'Plan to Read',
    ]);

    // Clear the activity log generated by the 'created' event
    ActivityLog::truncate();

    $series->update([
        'title' => 'Updated Title',
        'status' => 'Currently Reading',
    ]);

    $log = ActivityLog::first();

    expect($log)->not->toBeNull()
        ->and($log->action)->toBe(ActivityLog::ACTION_EDITED)
        ->and($log->series_id)->toBe($series->id)
        ->and($log->user_id)->toBe($user->id)
        ->and($log->description)->toContain("Changed title from 'Original Title' to 'Updated Title'")
        ->and($log->description)->toContain("Changed status from 'Plan to Read' to 'Currently Reading'")
        ->and($log->metadata['changed_fields'])->toBe(['title', 'status']);
});
